// GENERATED by tools/gen_effective_cfg.py from dp/src/dp/reset.hpp -- do not edit.
// Every global resetInvocationState sets to a constant, with its current value: read
// right after that reset, the core's built-in default profile.
#pragma once
#include <atomic>
#include <cstdio>
#include <string>
#include <type_traits>
#include <vector>

namespace dp {
namespace effdef {
template <class T> struct IsAtomic : std::false_type {};
template <class T> struct IsAtomic<std::atomic<T>> : std::true_type {};
template <class T> struct IsVector : std::false_type {};
template <class T, class A> struct IsVector<std::vector<T, A>> : std::true_type {};

template <class T> inline void one(std::string& s, const T& v) {
    if constexpr (IsAtomic<T>::value) {
        one(s, v.load());
    } else if constexpr (std::is_same_v<T, bool>) {
        s += v ? "1" : "0";
    } else if constexpr (std::is_enum_v<T>) {
        s += std::to_string((long long)v);
    } else if constexpr (std::is_integral_v<T>) {
        s += std::to_string(v);
    } else if constexpr (std::is_floating_point_v<T>) {
        char b[40];
        std::snprintf(b, sizeof(b), "%.9g", (double)v);
        s += b;
    } else if constexpr (std::is_pointer_v<T>) {
        // before the string case: a null `const char*` would be read as a string and crash
        if (!v) {
            s += "null";
        } else if constexpr (std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, char>) {
            one(s, std::string(v));
        } else {
            s += "set";
        }
    } else if constexpr (std::is_convertible_v<T, std::string>) {
        const std::string t(v);
        if (t.empty()) s += "-";
        for (char c : t) s += (c == ' ') ? '_' : c;
    } else if constexpr (IsVector<T>::value) {
        if (v.empty()) s += "-";
        for (size_t i = 0; i < v.size(); ++i) {
            if (i) s += ';';
            one(s, v[i]);
        }
    } else {
        s += "?";
    }
}

template <class... T> inline void put(std::string& s, const char* key, const T&... v) {
    if (!s.empty()) s += ' ';
    s += key;
    s += '=';
    int i = 0;
    auto item = [&](const auto& x) {
        if (i++) s += ',';
        one(s, x);
    };
    (item(v), ...);
}
}  // namespace effdef

inline std::string defaultsProfile() {
    using effdef::put;
    std::string s;
    put(s, "g_startBandKind", g_startBandKind);
    put(s, "g_startBandFloor", g_startBandFloor);
    put(s, "g_startBandCeil", g_startBandCeil);
    put(s, "g_bandTrackCam", g_bandTrackCam);
    put(s, "g_bandTrackEnd", g_bandTrackEnd);
    put(s, "g_bandK", g_bandK);
    put(s, "g_slopeDbg", g_slopeDbg);
    put(s, "g_slopeRelDbg", g_slopeRelDbg);
    put(s, "g_fxWatchT", g_fxWatchT);
    put(s, "g_vyWatchT", g_vyWatchT);
    put(s, "g_vyWriter", g_vyWriter);
    put(s, "g_vyWrites", g_vyWrites);
    put(s, "g_yWriter", g_yWriter);
    put(s, "g_yWrites", g_yWrites);
    put(s, "g_yIn", g_yIn);
    put(s, "g_vyIn", g_vyIn);
    put(s, "g_seatGateSeen", g_seatGateSeen);
    put(s, "g_impulseSite", g_impulseSite);
    put(s, "g_vpWrites", g_vpWrites);
    put(s, "g_impCount", g_impCount);
    put(s, "g_vyWatchT2", g_vyWatchT2);
    put(s, "g_dcyDbg", g_dcyDbg);
    put(s, "g_bandDbg", g_bandDbg);
    put(s, "g_spdDbg", g_spdDbg);
    put(s, "g_shipCeilSet", g_shipCeilSet);
    put(s, "g_clearProbe", g_clearProbe);
    put(s, "g_hazDbgUid", g_hazDbgUid);
    put(s, "g_hazAabb", g_hazAabb);
    put(s, "g_inRecon", g_inRecon);
    put(s, "g_dieRecon", g_dieRecon);
    put(s, "g_resimDead", g_resimDead);
    put(s, "g_resimTicks", g_resimTicks);
    put(s, "g_resimFirst", g_resimFirst);
    put(s, "g_resimLast", g_resimLast);
    put(s, "g_resimWhy", g_resimWhy);
    put(s, "g_trigDbgT", g_trigDbgT);
    put(s, "g_gfireGroups", g_gfireGroups);
    put(s, "g_gfireSpread", g_gfireSpread);
    put(s, "g_gfireSum", g_gfireSum);
    put(s, "g_gfireMax", g_gfireMax);
    put(s, "g_resimUid", g_resimUid);
    put(s, "g_resimObjX", g_resimObjX);
    put(s, "g_resimObjY", g_resimObjY);
    put(s, "g_resimFrame", g_resimFrame);
    put(s, "g_halfNow", g_halfNow);
    put(s, "g_pinMinNoSwing", g_pinMinNoSwing);
    put(s, "g_groupHoldEnd", g_groupHoldEnd);
    put(s, "g_groupsEndT", g_groupsEndT);
    put(s, "g_groupHoldDeath", g_groupHoldDeath);
    put(s, "g_noPadPlayerRot", g_noPadPlayerRot);
    put(s, "g_noSatRotRaw", g_noSatRotRaw);
    put(s, "g_oldLatency", g_oldLatency);
    put(s, "g_oldSlope", g_oldSlope);
    put(s, "g_ceilPin", g_ceilPin);
    put(s, "g_coinRoute", g_coinRoute);
    put(s, "g_coinMaskSeed", g_coinMaskSeed);
    put(s, "g_coinSkip", g_coinSkip);
    put(s, "g_shipCeil", g_shipCeil);
    put(s, "g_flyFloor", g_flyFloor);
    put(s, "g_ufoCeil", g_ufoCeil);
    put(s, "g_trigRaw", g_trigRaw);
    put(s, "g_lagFitDbg", g_lagFitDbg);
    put(s, "g_touchEnteredGiven", g_touchEnteredGiven);
    put(s, "g_dynDbg", g_dynDbg);
    put(s, "g_formulaDriven", g_formulaDriven);
    put(s, "g_rotSeen", g_rotSeen);
    put(s, "g_rotRouted", g_rotRouted);
    put(s, "g_rotCheck", g_rotCheck);
    put(s, "g_rotSplit", g_rotSplit);
    put(s, "g_shiftStat", g_shiftStat);
    put(s, "g_lockBox", g_lockBox);
    put(s, "g_lockTicks", g_lockTicks);
    put(s, "g_fixupConflictFilter", g_fixupConflictFilter);
    put(s, "g_fixupHits", g_fixupHits);
    put(s, "g_fixupRotSeen", g_fixupRotSeen);
    put(s, "g_fixupCallRotSeen", g_fixupCallRotSeen);
    put(s, "g_rotQChans", g_rotQChans);
    put(s, "g_rotQueue", g_rotQueue);
    put(s, "g_rotWatchLo", g_rotWatchLo);
    put(s, "g_rotWatchHi", g_rotWatchHi);
    put(s, "g_qfoldLo", g_qfoldLo);
    put(s, "g_qfoldHi", g_qfoldHi);
    put(s, "g_rotQToggle", g_rotQToggle);
    put(s, "g_touchCensus", g_touchCensus);
    put(s, "g_tcBranch", g_tcBranch);
    put(s, "g_tcBranchP1", g_tcBranchP1);
    put(s, "g_ceilPush", g_ceilPush);
    put(s, "g_flipLandDbgLeft", g_flipLandDbgLeft);
    put(s, "g_dualBand", g_dualBand);
    put(s, "g_dualSlide", g_dualSlide);
    put(s, "g_anchorRide", g_anchorRide);
    put(s, "g_stripVetoOrder", g_stripVetoOrder);
    put(s, "g_vetoPhys", g_vetoPhys);
    put(s, "g_verdictInfo", g_verdictInfo);
    put(s, "g_resimPX", g_resimPX);
    put(s, "g_preBtnSet", g_preBtnSet);
    put(s, "g_preBtnY", g_preBtnY);
    put(s, "g_ballTapped", g_ballTapped);
    put(s, "g_hitGRepel", g_hitGRepel);
    put(s, "g_startRotChan", g_startRotChan);
    put(s, "g_startRotRev", g_startRotRev);
    put(s, "g_seedDump", g_seedDump);
    put(s, "g_seedEvery", g_seedEvery);
    put(s, "g_p2Touch", g_p2Touch);
    put(s, "g_ownsTouch", g_ownsTouch);
    put(s, "g_ownsPortal", g_ownsPortal);
    put(s, "g_ownsHist", g_ownsHist);
    put(s, "g_seedPartialOk", g_seedPartialOk);
    put(s, "g_spentPadSeed", g_spentPadSeed);
    put(s, "g_baseLv", g_baseLv);
    put(s, "g_freeModeCol", g_freeModeCol);
    put(s, "g_trigGateCol", g_trigGateCol);
    put(s, "g_staticCamCol", g_staticCamCol);
    put(s, "g_bucketX0", g_bucketX0);
    put(s, "g_shipYq", g_shipYq);
    put(s, "g_shipVq", g_shipVq);
    put(s, "g_cubeYq", g_cubeYq);
    put(s, "g_cubeVq", g_cubeVq);
    put(s, "g_dualFreeQ", g_dualFreeQ);
    put(s, "g_heldKeyRead", g_heldKeyRead);
    put(s, "g_keyXq", g_keyXq);
    put(s, "g_keyXqFly", g_keyXqFly);
    put(s, "g_startSpeedMul", g_startSpeedMul);
    put(s, "g_dynHazPad", g_dynHazPad);
    put(s, "g_fixRadiusCollision", g_fixRadiusCollision);
    put(s, "g_fixGravityBug", g_fixGravityBug);
    put(s, "g_fixNegativeScale", g_fixNegativeScale);
    put(s, "g_fixRobotJump", g_fixRobotJump);
    put(s, "g_dynamicLevelHeight", g_dynamicLevelHeight);
    put(s, "g_maxPlayY", g_maxPlayY);
    put(s, "g_goalSpare", g_goalSpare);
    put(s, "g_upsideCoyote", g_upsideCoyote);
    put(s, "g_rawValues", g_rawValues);
    put(s, "g_portalUnpin", g_portalUnpin);
    put(s, "g_hazEndpoint", g_hazEndpoint);
    put(s, "g_portalPress", g_portalPress);
    put(s, "g_padTable", g_padTable);
    put(s, "g_flyRingNested", g_flyRingNested);
    put(s, "g_prePortalUid", g_prePortalUid);
    put(s, "g_ballTapNested", g_ballTapNested);
    put(s, "g_ballTapLaunch", g_ballTapLaunch);
    put(s, "g_heldAll", g_heldAll);
    put(s, "g_heldCellCap", g_heldCellCap);
    put(s, "g_heldCellTwins", g_heldCellTwins);
    put(s, "g_histStatOn", g_histStatOn);
    put(s, "g_goalX", g_goalX);
    put(s, "g_offBoardMargin", g_offBoardMargin);
    put(s, "g_shiftDbgUid", g_shiftDbgUid);
    put(s, "g_shiftDbgDone", g_shiftDbgDone);
    put(s, "g_snapOut", g_snapOut);
    put(s, "g_threads", g_threads);
    put(s, "g_aliveCap", g_aliveCap);
    put(s, "g_memStat", g_memStat);
    put(s, "g_phaseProf", g_phaseProf);
    put(s, "g_gcNodes", g_gcNodes);
    put(s, "g_memLimitMiB", g_memLimitMiB);
    put(s, "g_portalDodgeMin", g_portalDodgeMin);
    put(s, "g_speedDodgeMin", g_speedDodgeMin);
    put(s, "g_glitchPortal", g_glitchPortal);
    put(s, "g_glitchWave", g_glitchWave);
    put(s, "g_glitchEmbed", g_glitchEmbed);
    put(s, "g_glitchDeco", g_glitchDeco);
    put(s, "g_coinWinY", g_coinWinY);
    put(s, "g_coinWinVy", g_coinWinVy);
    put(s, "g_coinWinLen", g_coinWinLen);
    put(s, "g_ladderX0", g_ladderX0);
    put(s, "g_capEnvelope", g_capEnvelope);
    put(s, "g_rotLast", g_rotLast);
    put(s, "g_yBound", g_yBound);
    put(s, "g_yBoundTurned", g_yBoundTurned);
    put(s, "g_touchFollowObjs", g_touchFollowObjs);
    put(s, "g_keyCensus", g_keyCensus);
    put(s, "g_searchCensus", g_searchCensus);
    put(s, "g_twinAudit", g_twinAudit);
    put(s, "g_minPulse", g_minPulse);
    put(s, "g_inputGrid", g_inputGrid);
    put(s, "g_coinProbeMaxX", g_coinProbeMaxX);
    put(s, "g_trigMaxKeptX", g_trigMaxKeptX);
    put(s, "g_needUnseen", g_needUnseen);
    put(s, "g_airPress", g_airPress);
    put(s, "g_refAdopt", g_refAdopt);
    put(s, "g_refAdoptT", g_refAdoptT);
    put(s, "g_obbAll", g_obbAll);
    put(s, "g_touchFromAnchor", g_touchFromAnchor);
    put(s, "g_trigDump", g_trigDump);
    put(s, "g_trigEffect", g_trigEffect);
    put(s, "g_stopDump", g_stopDump);
    put(s, "g_trigWinNear", g_trigWinNear);
    put(s, "g_spawnRemap", g_spawnRemap);
    put(s, "g_touchRetimeFrom", g_touchRetimeFrom);
    put(s, "g_fbForceBox", g_fbForceBox);
    put(s, "g_fbForceTick", g_fbForceTick);
    put(s, "g_replayOn", g_replayOn);
    put(s, "g_fgArmLive", g_fgArmLive);
    put(s, "g_fireBCheck", g_fireBCheck);
    put(s, "g_groupFire", g_groupFire);
    put(s, "g_groupXSplit", g_groupXSplit);
    put(s, "g_groupXSplitLayers", g_groupXSplitLayers);
    put(s, "g_groupXSplitMax", g_groupXSplitMax);
    put(s, "g_fireBNoTick", g_fireBNoTick);
    put(s, "g_fireBNoBit", g_fireBNoBit);
    put(s, "g_fireBTooEarly", g_fireBTooEarly);
    put(s, "g_refWatch", g_refWatch);
    put(s, "g_rjOn", g_rjOn);
    put(s, "g_rjAfter", g_rjAfter);
    put(s, "g_rjLayers", g_rjLayers);
    put(s, "g_rjUse", g_rjUse);
    put(s, "g_rjFull", g_rjFull);
    put(s, "g_rjJoinT", g_rjJoinT);
    put(s, "g_refEps", g_refEps);
    put(s, "g_refDriftVy", g_refDriftVy);
    put(s, "g_refDriftY", g_refDriftY);
    put(s, "g_refParent", g_refParent);
    put(s, "g_refLostAt", g_refLostAt);
    return s;
}

}  // namespace dp
