#!/usr/bin/env python
"""What a cold run measured, written beside its logs -- and the check that two runs differ
only where they are meant to.

    python py/cold_manifest.py show <run dir | manifest.json>
    python py/cold_manifest.py compare <A> <B> [--allow KEY ...] [--allow-binary]
    python py/cold_manifest.py check <run> [--expect key=v ...] [--expect-dp name=v ...] [--allow KEY ...]

A run's NAME is not a description of it. A whole day of "base" and "default" arms once turned
out to carry an extra `dparg` that nobody had meant to keep, and every comparison between them
had been read as if the only difference were the flag under test. So the run writes down what
it was, and the comparison reads that record instead of the folder names:

  head / dirty     the commit the package was built from and whether tracked files were
                   modified -- from the build's provenance.json when it matches the package,
                   else the checkout the driver ran from (driver_head / driver_dirty keep that)
  mod / sha256     the package the workers loaded (the pinned copy, hashed before the run)
  cfg              every autorun.cfg key the workers were given: the driver's fixed ones and
                   the run's own, in order
  coins            the coin condition the cfg amounts to (on / off / neither)
  levels           per level, the flags of the first solver call the mod made, as it logged
                   them (`dpsolve: solver args:`), so a cfg key the mod ignored or a flag it
                   added on its own is visible in the record, not inferred
  effective_cfg    every cfg key's value as the mod held it at solve start (`cfgeff:`), and
  dp_defaults      the core's built-in defaults (`dpdefaults:`) -- a default shows in neither
                   the cfg nor the argv; per level, which keys differed from their default
                   (`cfgdiff:`). `check` reads these before a bless.
  sources          per level, where it came from and a hash of its content (`levelsource:`:
                   main / file / saved), so the same ID from different level data is not
                   compared as the same run
  ride_pairing     per level, the anchored solver calls counted by the hist payload's version
                   (4 carries the slope ride's facts) against dp's ride consumer for that call;
                   `check` refuses a call where the two disagree

`compare` refuses (exit 2) when the two runs differ in anything but the cfg keys named with
--allow: a different commit or package (unless --allow-binary), a dirty tree, another
resolution or arrangement, or a cfg key nobody named. The solver flags are printed per level
either way; with the same cfg and the same package they must be identical, and a difference
there is refused too, because then the mod decided something the cfg does not show.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import time
from pathlib import Path

NAME = "cold_manifest.json"
ARGS_LINE = re.compile(r"^dpsolve: solver args:(.*)$", re.M)
# The three lines the mod prints at solve start (repair.hpp dpsolve::start, generated by
# tools/gen_effective_cfg.py): every cfg key's value, the keys that differ from the defaults, and
# the core's built-in defaults.
EFF_LINE = re.compile(r"^cfgeff: (.*)$", re.M)
DIFF_LINE = re.compile(r"^cfgdiff: (.*)$", re.M)
DPDEF_LINE = re.compile(r"^dpdefaults: (.*)$", re.M)
# Which level a run played, by content (level_entry.hpp): kind main / file / saved.
SOURCE_LINE = re.compile(r"^levelsource: id=(\d+) kind=(\w+) sig=([0-9a-f]+) bytes=(\d+)$", re.M)
PER_LEVEL_KEYS = {"level", "levelfile"}   # differ between the levels of one run by design
# Keys the mod's parser sets as a consequence of another key (session.hpp): accepted by `check`
# only when the key that implies them was written with that value.
IMPLIED = {"grouptrace": ("dpsolve", "1")}   # a solve records its moving geometry
# Values that change from one call to the next or name a file; the flag is kept, the value is
# not, so two runs of the same configuration produce the same record.
PER_CALL = {"--out", "--start", "--startband", "--anchor-state", "--touchentered", "--spentorb",
            "--startrotq", "--coinmask", "--bandtrackend", "--rejoinafter", "--rejoinwatch"}
# The anchor's ride facts are one unit in two halves: the mod's cfg histride writes them (hist
# payload version 4) and dp's --anchorride consumes them. Counted per anchored call, so a run
# where the two disagree -- a recording nobody reads, or a consumer given a payload without the
# facts -- is visible in the record rather than inferred from the cfg.
HIST_VERSION = re.compile(r"--anchor-state \S*?\bhist=(\d+)\|")


def _git(*args: str) -> str:
    return subprocess.run(["git", *args], capture_output=True, text=True,
                          cwd=Path(__file__).resolve().parent).stdout.strip()


def read_provenance(mod: Path) -> dict | None:
    """The build's own record of what it was built from (`provenance.json` beside the package:
    commit, tree, dirty, mod_sha256, leveldp_sha256), or None when there is none or it is not
    this package's. A package run from another checkout -- an arm's copy, a detached worktree
    -- keeps its identity this way; the checkout the driver runs from says nothing about it."""
    p = Path(mod).with_name("provenance.json")
    try:
        prov = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    sha = hashlib.sha256(Path(mod).read_bytes()).hexdigest()
    if str(prov.get("mod_sha256", "")).lower() != sha:
        print(f"  {p} is not this package's (its mod_sha256 {str(prov.get('mod_sha256'))[:12]}"
              f" against {sha[:12]}): the manifest keeps the driver's head")
        return None
    return prov


def start(out_dir: Path, *, mod: Path, cfg: list[str], levels: list[int], arrangement: str,
          resolution: int | None, coins: bool | None, build: dict | None = None) -> dict:
    """The part known before the run, written at once: the package is hashed here, before a
    build that lands mid-run could change what a later hash reads.

    `build` is the package's provenance (read_provenance). With it, head and dirty are the
    BUILD's, and the checkout the driver ran from is kept apart as driver_head -- so two runs
    of one package from different checkouts compare as the same package, and a run of another
    package from the same checkout does not pass as the same commit."""
    driver_head = _git("rev-parse", "HEAD")
    driver_dirty = bool(_git("status", "--porcelain", "--untracked-files=no"))
    m = {"written": time.strftime("%Y-%m-%d %H:%M:%S"), "t0": time.time(),
         "head": build["commit"] if build else driver_head,
         "dirty": bool(build["dirty"]) if build else driver_dirty,
         "driver_head": driver_head, "driver_dirty": driver_dirty,
         "build": build,
         "mod": str(mod), "mod_sha256": hashlib.sha256(Path(mod).read_bytes()).hexdigest(),
         "cfg": list(cfg), "coins": {True: "on", False: "off", None: "neither"}[coins],
         "arrangement": arrangement, "resolution": resolution,
         "levels": {str(lv): None for lv in levels}}
    (out_dir / NAME).write_text(json.dumps(m, indent=1), encoding="utf-8")
    return m


def solver_flags(log: str) -> dict | None:
    """The first solver call's flags: {flag: value}, with None for a flag without a value or
    one whose value is per-call or a path. None when the log has no solver call."""
    m = ARGS_LINE.search(log)
    if not m:
        return None
    toks = m.group(1).split()
    out: dict = {}
    i = 0
    while i < len(toks):
        t = toks[i]
        if not t.startswith("--"):
            i += 1
            continue
        val = toks[i + 1] if i + 1 < len(toks) and not toks[i + 1].startswith("--") else None
        if val is not None and (t in PER_CALL or "/" in val or "\\" in val):
            keep = None
        else:
            keep = val
        # a flag given more than once (--groups, --needtrig-skip) keeps every value
        if t in out:
            prev = out[t] if isinstance(out[t], list) else [out[t]]
            out[t] = prev + [keep]
        else:
            out[t] = keep
        i += 2 if val is not None else 1
    return out


def ride_pairing(log: str, consumer_default: bool) -> dict:
    """Per anchored solver call: the hist payload's version (4 carries the ride's facts, below
    4 does not) against whether dp's consumer was on for that call (its built-in default, then
    --anchorride / --no-anchorride in argv order). Four counts; the two mixed ones must be 0."""
    out = {"v4_on": 0, "v4_off": 0, "old_on": 0, "old_off": 0}
    for args in ARGS_LINE.findall(log):
        v = HIST_VERSION.search(args)
        if not v:
            continue
        on = consumer_default
        for t in args.split():
            if t == "--anchorride":
                on = True
            elif t == "--no-anchorride":
                on = False
        out[("v4" if int(v.group(1)) >= 4 else "old") + ("_on" if on else "_off")] += 1
    return out


def _pairs(s: str) -> dict:
    out: dict = {}
    for tok in s.split():
        k, _, v = tok.partition("=")
        out[k] = v
    return out


def effective(log: str) -> dict | None:
    """The first solve's effective values, from the lines the mod prints at solve start:
    {"cfg": {key: value}, "changed": {key: value}, "dp": {name: value}, "dp_fnv", "core"}.
    None when the log has none of them (a build before the lines existed)."""
    e, d, p = EFF_LINE.search(log), DIFF_LINE.search(log), DPDEF_LINE.search(log)
    if not e and not p:
        return None
    out: dict = {"cfg": _pairs(e.group(1)) if e else {}, "changed": {}, "dp": {},
                 "dp_fnv": None, "core": None}
    if d and d.group(1).strip() not in ("-",) and not d.group(1).startswith("("):
        for tok in d.group(1).split():
            k, _, rest = tok.partition("=")
            out["changed"][k] = re.sub(r"\([^()]*\)$", "", rest)
    if p:
        dp = _pairs(p.group(1))
        out["core"] = dp.pop("core", None)
        out["dp_fnv"] = dp.pop("fnv", None)
        out["dp"] = dp
    return out


def finish(out_dir: Path, logs: dict[int, Path]) -> dict:
    """Add each level's solver flags and effective values, read from that level's log -- only a
    log written after the run started, so a level that never ran does not inherit a file from an
    earlier run. The full effective cfg and the core defaults are stored once (from the first
    level that has them); each level records whether its own match, and what it changed."""
    p = out_dir / NAME
    m = json.loads(p.read_text(encoding="utf-8"))
    eff_levels: dict = {}
    for lv, f in logs.items():
        try:
            if f.stat().st_mtime < m["t0"]:
                m["levels"][str(lv)] = "stale log (older than the run)"
                continue
            text = f.read_text(encoding="utf-8", errors="replace")
            m["levels"][str(lv)] = solver_flags(text)
            src = [s for s in SOURCE_LINE.findall(text) if int(s[0]) == int(lv)]
            if src:
                m.setdefault("sources", {})[str(lv)] = {"kind": src[0][1], "sig": src[0][2],
                                                        "bytes": int(src[0][3])}
            e = effective(text)
            m.setdefault("ride_pairing", {})[str(lv)] = ride_pairing(
                text, bool(e) and e["dp"].get("g_anchorRide") == "1")
            if e is None:
                continue
            cfg = {k: v for k, v in e["cfg"].items() if k not in PER_LEVEL_KEYS}
            if "effective_cfg" not in m:
                m["effective_cfg"] = cfg
                m["dp_defaults"] = e["dp"]
                m["dp_fnv"] = e["dp_fnv"]
                m["core"] = e["core"]
            eff_levels[str(lv)] = {"cfg_same": cfg == m["effective_cfg"],
                                   "changed": {k: v for k, v in e["changed"].items()
                                               if k not in PER_LEVEL_KEYS},
                                   "dp_fnv": e["dp_fnv"]}
        except OSError:
            m["levels"][str(lv)] = "no log"
    if eff_levels:
        m["effective_levels"] = eff_levels
    p.write_text(json.dumps(m, indent=1), encoding="utf-8")
    return m


def load(path: Path) -> dict:
    path = Path(path)
    return json.loads((path / NAME if path.is_dir() else path).read_text(encoding="utf-8"))


def _cfg_map(cfg: list[str]) -> dict:
    out: dict = {}
    for kv in cfg:
        k, _, v = kv.partition("=")
        out.setdefault(k, []).append(v)
    return out


def compare(a: dict, b: dict, allow: set[str], allow_binary: bool) -> int:
    refuse: list[str] = []
    for k in ("head", "mod_sha256"):
        if a[k] != b[k]:
            (print if allow_binary else refuse.append)(f"{k}: {a[k][:12]} vs {b[k][:12]}")
    for side, m in (("A", a), ("B", b)):
        if m.get("dirty"):
            refuse.append(f"{side} ran from a tree with modified tracked files")
    for k in ("arrangement", "resolution"):
        if a.get(k) != b.get(k):
            line = f"{k}: {a.get(k)} vs {b.get(k)}"
            if k in allow:
                print(line)
            else:
                refuse.append(line + " (name it with --allow to accept)")
    ca, cb = _cfg_map(a["cfg"]), _cfg_map(b["cfg"])
    differs = sorted(k for k in set(ca) | set(cb) if ca.get(k) != cb.get(k))
    for k in differs:
        line = f"cfg {k}: {ca.get(k, '-')} vs {cb.get(k, '-')}"
        print(line if k in allow else line + "  <- not allowed")
        if k not in allow:
            refuse.append(f"cfg key {k} differs and was not named with --allow")
    print(f"coins: {a.get('coins')} vs {b.get('coins')}")
    # The effective values (runs whose mod printed them): a key nobody wrote is compared here.
    ea, eb = a.get("effective_cfg"), b.get("effective_cfg")
    if ea is not None and eb is not None:
        # a suite's own list (`levels`) is what an allowed change of arrangement changes
        arr_ok = "arrangement" in allow and a.get("arrangement") != b.get("arrangement")
        for k in sorted(set(ea) | set(eb)):
            if k == "levels" and arr_ok:
                continue
            if ea.get(k) != eb.get(k):
                line = f"effective {k}: {ea.get(k, '-')} vs {eb.get(k, '-')}"
                print(line if k in allow else line + "  <- not allowed")
                if k not in allow:
                    refuse.append(f"effective cfg {k} differs and was not named with --allow")
        if a.get("dp_fnv") != b.get("dp_fnv"):
            da, db = a.get("dp_defaults") or {}, b.get("dp_defaults") or {}
            names = sorted(k for k in set(da) | set(db) if da.get(k) != db.get(k))
            print(f"core defaults differ ({a.get('dp_fnv')} vs {b.get('dp_fnv')}): "
                  + ", ".join(f"{k} {da.get(k, '-')}->{db.get(k, '-')}" for k in names))
            if not allow_binary:
                refuse.append("the core's built-in defaults differ (a different build)")
    elif (ea is None) != (eb is None):
        print("effective values: recorded by only one of the two runs")
    # The levels themselves, by content: the same ID from a different file is a different run.
    sa, sb = a.get("sources") or {}, b.get("sources") or {}
    for lv in sorted(set(sa) & set(sb), key=int):
        if sa[lv] != sb[lv]:
            line = f"lv{lv} source: {sa[lv]} vs {sb[lv]}"
            print(line if "levelsource" in allow else line + "  <- not allowed")
            if "levelsource" not in allow:
                refuse.append(f"lv{lv} was played from different level data")
    same_cfg_and_pkg = not differs and a["mod_sha256"] == b["mod_sha256"]
    for lv in sorted(set(a["levels"]) & set(b["levels"]), key=int):
        fa, fb = a["levels"][lv], b["levels"][lv]
        if not isinstance(fa, dict) or not isinstance(fb, dict):
            print(f"lv{lv}: flags not comparable ({fa!r} / {fb!r})")
            continue
        only_a = sorted(set(fa) - set(fb))
        only_b = sorted(set(fb) - set(fa))
        valued = sorted(k for k in set(fa) & set(fb) if fa[k] != fb[k])
        if only_a or only_b or valued:
            print(f"lv{lv}: flags only in A {only_a or '-'}, only in B {only_b or '-'}"
                  + (f", values differ {valued}" if valued else ""))
            if same_cfg_and_pkg:
                refuse.append(f"lv{lv}: the same cfg and package gave different solver flags")
    if refuse:
        print("REFUSED:")
        for r in refuse:
            print("  " + r)
        return 2
    print("comparable: " + (f"differs only in {', '.join(differs)}" if differs else "same cfg")
          + ("" if a["mod_sha256"] == b["mod_sha256"] else " (and the package, allowed)"))
    return 0


def check(m: dict, expect: list[str], expect_dp: list[str], allow: set[str]) -> int:
    """What a run actually ran with, before it is blessed: every level recorded its effective
    values and they agree, each expected value holds, and no key differs from its default unless
    the driver wrote it (or it is named with --allow) -- a diagnostic or experimental switch left
    on shows up here and nowhere else."""
    refuse: list[str] = []
    if "effective_cfg" not in m:
        print("REFUSED:\n  this run recorded no effective values (a build before cfgeff:)")
        return 2
    levels = m.get("effective_levels", {})
    missing = sorted((lv for lv in m["levels"] if lv not in levels), key=int)
    if missing:
        refuse.append(f"no effective values for levels {', '.join(missing)}")
    nosrc = sorted((lv for lv in m["levels"] if lv not in (m.get("sources") or {})), key=int)
    if nosrc:
        refuse.append(f"no levelsource line for levels {', '.join(nosrc)}")
    for lv, e in sorted(levels.items(), key=lambda kv: int(kv[0])):
        if not e["cfg_same"]:
            refuse.append(f"lv{lv}: its effective cfg differs from the first level's")
        if e["dp_fnv"] != m.get("dp_fnv"):
            refuse.append(f"lv{lv}: core defaults {e['dp_fnv']} differ from {m.get('dp_fnv')}")
    ride = m.get("ride_pairing") or {}
    tot = {k: sum(p[k] for p in ride.values()) for k in ("v4_on", "v4_off", "old_on", "old_off")}
    print("anchored calls, hist payload x ride consumer: "
          + " ".join(f"{k}={v}" for k, v in tot.items()))
    for lv, p in sorted(ride.items(), key=lambda kv: int(kv[0])):
        if p["v4_off"]:
            refuse.append(f"lv{lv}: {p['v4_off']} anchored call(s) carried the ride's facts "
                          "(hist version 4) with dp's consumer off")
        if p["old_on"]:
            refuse.append(f"lv{lv}: {p['old_on']} anchored call(s) ran dp's ride consumer on a "
                          "payload without the ride's facts (cfg histride and --anchorride disagree)")
    wmap = _cfg_map(m["cfg"])
    written = set(wmap)
    unexplained: dict = {}
    for lv, e in levels.items():
        for k, v in e["changed"].items():
            if k in written or k in allow:
                continue
            if k == "levels" and m.get("arrangement") == "one-session":
                continue   # the suite's list, which the driver adds to the cfg itself
            by = IMPLIED.get(k)
            if by and by[1] in wmap.get(by[0], []):
                continue
            unexplained.setdefault(k, set()).add(v)
    for k, vs in sorted(unexplained.items()):
        refuse.append(f"{k}={','.join(sorted(vs))} differs from its default, and nobody wrote it")
    for kv in expect:
        k, _, v = kv.partition("=")
        got = m["effective_cfg"].get(k)
        print(f"cfg {k}={got}" + ("" if got == v else f"  <- expected {v}"))
        if got != v:
            refuse.append(f"cfg {k} is {got}, not {v}")
    for kv in expect_dp:
        k, _, v = kv.partition("=")
        got = (m.get("dp_defaults") or {}).get(k)
        print(f"core {k}={got}" + ("" if got == v else f"  <- expected {v}"))
        if got != v:
            refuse.append(f"core default {k} is {got}, not {v}")
    print(f"core {m.get('core')} defaults {m.get('dp_fnv')}; {len(levels)} level(s) recorded")
    if refuse:
        print("REFUSED:")
        for r in refuse:
            print("  " + r)
        return 2
    print("checked: every level ran what the driver wrote on top of the defaults")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("show")
    s.add_argument("run", type=Path)
    k = sub.add_parser("check")
    k.add_argument("run", type=Path)
    k.add_argument("--expect", nargs="*", default=[], help="cfg key=value that must hold")
    k.add_argument("--expect-dp", nargs="*", default=[], help="core default name=value")
    k.add_argument("--allow", nargs="*", default=[],
                   help="keys that may differ from their default without being written")
    c = sub.add_parser("compare")
    c.add_argument("a", type=Path)
    c.add_argument("b", type=Path)
    c.add_argument("--allow", nargs="*", default=[],
                   help="cfg keys the two runs may differ in, or `arrangement` / `resolution`")
    c.add_argument("--allow-binary", action="store_true",
                   help="the runs may come from different commits / packages")
    a = ap.parse_args(argv)
    if a.cmd == "show":
        print(json.dumps(load(a.run), indent=1))
        return 0
    if a.cmd == "check":
        return check(load(a.run), a.expect, a.expect_dp, set(a.allow))
    return compare(load(a.a), load(a.b), set(a.allow), a.allow_binary)


if __name__ == "__main__":
    sys.exit(main())
