// GENERATED by tools/gen_effective_cfg.py from src/mod/session.hpp -- do not edit.
// Every autorun.cfg key the mod's parser knows, with the value of what it sets.
#pragma once
#include <atomic>
#include <cstdio>
#include <string>
#include <type_traits>
#include <vector>

namespace p1 {
namespace effcfg {
template <class T> struct IsAtomic : std::false_type {};
template <class T> struct IsAtomic<std::atomic<T>> : std::true_type {};
template <class T> struct IsVector : std::false_type {};
template <class T, class A> struct IsVector<std::vector<T, A>> : std::true_type {};

template <class T> inline void one(std::string& s, const T& v) {
    if constexpr (IsAtomic<T>::value) {
        one(s, v.load());
    } else if constexpr (std::is_same_v<T, bool>) {
        s += v ? "1" : "0";
    } else if constexpr (std::is_enum_v<T>) {
        s += std::to_string((long long)v);
    } else if constexpr (std::is_integral_v<T>) {
        s += std::to_string(v);
    } else if constexpr (std::is_floating_point_v<T>) {
        char b[40];
        std::snprintf(b, sizeof(b), "%.9g", (double)v);
        s += b;
    } else if constexpr (std::is_pointer_v<T>) {
        // before the string case: a null `const char*` would be read as a string and crash
        if (!v) {
            s += "null";
        } else if constexpr (std::is_same_v<std::remove_cv_t<std::remove_pointer_t<T>>, char>) {
            one(s, std::string(v));
        } else {
            s += "set";
        }
    } else if constexpr (std::is_convertible_v<T, std::string>) {
        const std::string t(v);
        if (t.empty()) s += "-";
        for (char c : t) s += (c == ' ') ? '_' : c;
    } else if constexpr (IsVector<T>::value) {
        if (v.empty()) s += "-";
        for (size_t i = 0; i < v.size(); ++i) {
            if (i) s += ';';
            one(s, v[i]);
        }
    } else {
        s += "?";
    }
}

template <class... T> inline void put(std::string& s, const char* key, const T&... v) {
    if (!s.empty()) s += ' ';
    s += key;
    s += '=';
    int i = 0;
    auto item = [&](const auto& x) {
        if (i++) s += ',';
        one(s, x);
    };
    (item(v), ...);
}

inline std::string modCfg() {
    std::string s;
    put(s, "areaenv", g_cfg.areaEnv);
    put(s, "framebudgetms", g_cfg.frameBudgetMs);
    put(s, "dplearnresets", g_cfg.dpLearnResets);
    put(s, "secsnapact", psnap::g_snapAct);
    put(s, "secactkey", psnap::g_actKey);
    put(s, "secdriftwhere", g_cfg.secDriftWhere);
    put(s, "dpcaptiers", g_cfg.dpCapTiers);
    put(s, "dpsectierfirst", g_cfg.dpSecTierFirst);
    put(s, "dpsecmaxback", g_cfg.dpSecMaxBack);
    put(s, "sectrail", secsolve::g_trailClear);
    put(s, "secgracefly", secsolve::g_graceFly);
    put(s, "secleafmid", secsolve::g_leafMid);
    put(s, "secleaflife", secsolve::g_leafLife);
    put(s, "secdrift", secsolve::g_driftLog);
    put(s, "secbound", secsolve::g_boundOn);
    put(s, "secshaderskip", secsolve::g_shaderSkip);
    put(s, "seccoins", secsolve::g_secCoins);
    put(s, "levelfiletype", g_cfg.levelFileMain);
    put(s, "leveldir", suite::g_levelDir);
    put(s, "enabled", g_cfg.enabled);
    put(s, "level", g_cfg.levelId);
    put(s, "levels", suite::g_levels);
    put(s, "levelfile", g_cfg.levelFile);
    put(s, "attempts", g_cfg.maxAttempts);
    put(s, "delay", g_cfg.delaySec);
    put(s, "quitwhendone", g_cfg.quitWhenDone);
    put(s, "fps", g_cfg.fps);
    put(s, "cbs", g_cfg.cbs);
    put(s, "cos", g_cfg.cos);
    put(s, "framedt", g_cfg.framedt);
    put(s, "slowmo", g_slowmo);
    put(s, "blockinput", g_cfg.blockInput);
    put(s, "progblock", g_cfg.progressBlock);
    put(s, "fastdt", g_cfg.fastdt);
    put(s, "fastloops", g_cfg.fastloops);
    put(s, "skiprender", g_cfg.skipRender);
    put(s, "watchspeed", g_watchIdx);
    put(s, "watchat", g_watchAtTick);
    put(s, "watchatx", g_watchAtX);
    put(s, "watchback", g_watchBackTicks);
    put(s, "watchafter", g_watchAfterSec);
    put(s, "watchcycle", g_watchCycleSec);
    put(s, "fxsweep", g_fxSweep);
    put(s, "visrefresh", g_visRefreshOn);
    put(s, "watchpurge", g_watchPurge);
    put(s, "endpurge", g_endPurge);
    put(s, "endburn", g_endzoneBurnOn);
    put(s, "syncprobe", g_syncProbe);
    put(s, "itermap", itermap::g_mapPref);
    put(s, "trigtrace", g_trigTrace);
    put(s, "gatetrace", solver::g_gateX1);
    put(s, "gatestride", solver::g_gateStride);
    put(s, "servemode", g_serveMode);
    put(s, "colprobe", solver::g_cpT, solver::g_cpY0, solver::g_cpYStep, solver::g_cpVy, solver::g_cpN);
    put(s, "gatetick", solver::g_gateT1);
    put(s, "lagms", g_lagMs);
    put(s, "lagat", g_lagAtTick);
    put(s, "speedgate", speedgate::g_gate);
    put(s, "deathfx", g_deathFx);
    put(s, "hud", g_hudOn);
    put(s, "retryafter", g_retryAfterSec);
    put(s, "notrace", g_cfg.noTrace);
    put(s, "hitboxes", hitbox::g_mode);
    put(s, "dumpearly", g_cfg.dumpEarly);
    put(s, "endtrace", g_cfg.endTrace);
    put(s, "orbtrace", g_cfg.orbTrace);
    put(s, "orbtracex", g_cfg.orbTraceX);
    put(s, "subringspent", g_cfg.subRingSpent);
    put(s, "padtrace", g_cfg.padTrace);
    put(s, "touchpayload", g_cfg.touchPayload);
    put(s, "portalpayload", g_cfg.portalPayload);
    put(s, "snaptrace", g_cfg.snapTrace);
    put(s, "hitboxtrace", g_cfg.hitboxTrace);
    put(s, "fieldprobe", g_cfg.fieldProbe);
    put(s, "killersite", g_cfg.killerSite);
    put(s, "hbfrom", g_cfg.hbFrom);
    put(s, "hbto", g_cfg.hbTo);
    put(s, "watchuid", g_cfg.watchUid);
    put(s, "standtrace", g_cfg.standTrace);
    put(s, "grouptrace", grouptrace::g_on);
    put(s, "grouptraceall", grouptrace::g_all);
    put(s, "groupstride", grouptrace::g_stride);
    put(s, "nodeath", g_cfg.noDeath);
    put(s, "clearance", clearance::g_on);
    put(s, "practiceat", g_cfg.practiceAt);
    put(s, "checkpointat", g_cfg.checkpointAt);
    put(s, "restoreat", g_cfg.restoreAt);
    put(s, "restoreloopkeep", g_cfg.restoreLoopKeep);
    put(s, "restoreloophold", g_cfg.restoreLoopHold);
    put(s, "restoreloopcycle", g_cfg.restoreLoopCycle);
    put(s, "restoreloopclearq", g_cfg.restoreLoopClearQ);
    put(s, "restoreloopdrain", g_cfg.restoreLoopDrain);
    put(s, "restoreloopheap", g_cfg.restoreLoopHeapMB);
    put(s, "restoreloopdrainat", g_cfg.restoreLoopDrainAt);
    put(s, "restoreloop", g_cfg.restoreLoop);
    put(s, "oobtest", g_cfg.oobTest);
    put(s, "vytest", g_cfg.vyTest);
    put(s, "snapverify", g_cfg.snapVerify);
    put(s, "robodbg", g_cfg.roboDbg0, g_cfg.roboDbg1);
    put(s, "snapat", g_cfg.snapAt);
    put(s, "secsolve", secsolve::g_on);
    put(s, "secstart", secsolve::g_startTick);
    put(s, "sectarget", secsolve::g_targetX);
    put(s, "sechorizon", secsolve::g_horizon);
    put(s, "seccap", secsolve::g_cap);
    put(s, "secverify", secsolve::g_verify);
    put(s, "secspine", secsolve::g_spineOn);
    put(s, "secdeadline", secsolve::g_deadlineSec);
    put(s, "secspineoff", secsolve::g_spineOff);
    put(s, "seclog", secsolve::g_log);
    put(s, "secdt", secsolve::g_dt);
    put(s, "secoff", secsolve::g_off);
    put(s, "secpsnap", secsolve::g_snapCmp);
    put(s, "secpsnapreps", secsolve::g_snapReps);
    put(s, "secsnap", secsolve::g_snapMode);
    put(s, "secrephase", secsolve::g_rephase);
    put(s, "secworld", secsolve::g_worldDiff);
    put(s, "secmaxmov", secsolve::g_maxMoving);
    put(s, "secnokill", secsolve::g_killOverride);
    put(s, "seckilllog", secsolve::g_killLog);
    put(s, "secvis", secsolve::g_visRefresh);
    put(s, "secpos", psnap::g_keepSnapPos);
    put(s, "secoverlay", secsolve::g_overlay);
    put(s, "secmasklo", psnap::g_maskLo);
    put(s, "secmaskhi", psnap::g_maskHi);
    put(s, "secskipextras", psnap::g_skipExtras);
    put(s, "secmemat", secsolve::g_memAt);
    put(s, "secmaskexlo", psnap::g_maskExLo);
    put(s, "secmaskexhi", psnap::g_maskExHi);
    put(s, "secsnapobj", psnap::g_snapCollideObj);
    put(s, "secwinshift", secsolve::g_winShift);
    put(s, "seccollog", secsolve::g_colLog);
    put(s, "secverifyevery", secsolve::g_verifyEvery);
    put(s, "secverifytol", secsolve::g_verifyTol);
    put(s, "secanchor", secsolve::g_anchor);
    put(s, "secyq", secsolve::g_yq);
    put(s, "secvq", secsolve::g_vq);
    put(s, "secdeadband", secsolve::g_secBands);
    put(s, "secxq", secsolve::g_xq);
    put(s, "secjumpbuf", secsolve::g_jumpBuf);
    put(s, "sectargety", secsolve::g_targetY);
    put(s, "sectargetydir", secsolve::g_targetYDir);
    put(s, "sectargetdepth", secsolve::g_targetDepth);
    put(s, "secgrace", secsolve::g_grace);
    put(s, "secmaxdoomed", secsolve::g_maxDoomed);
    put(s, "secmaxy", secsolve::g_maxY);
    put(s, "secslicems", secsolve::g_sliceMs);
    put(s, "notifytest", notify::g_test);
    put(s, "notifyfix", notify::g_fix);
    put(s, "music", g_cfg.music);
    put(s, "heapcheck", g_heapCheckEvery);
    put(s, "ckpttrace", solver::ckpttrace::g_on);
    put(s, "pauseatx", g_pauseAtX);
    put(s, "clearmargin", g_clearMargin);
    put(s, "uisim", g_uiSession);
    put(s, "uimode", g_uiMode);
    put(s, "coins", g_cfg.coinMode);
    put(s, "coinroute", g_cfg.coinRoute);
    put(s, "coinwatch", g_cfg.coinWatch);
    put(s, "toggle", g_cfg.toggles);
    put(s, "input", g_cfg.inputs);
    put(s, "dpselftest", g_cfg.dpSelfTest);
    put(s, "dpsolve", g_cfg.dpSolve);
    put(s, "dphorizon", g_cfg.dpHorizon);
    put(s, "dpstephorizon", g_cfg.dpStepHorizon);
    put(s, "dpfastvetoall", g_cfg.dpFastVetoAll);
    put(s, "dprejoinfull", g_cfg.dpRejoinFull);
    put(s, "dpoffboardkill", g_cfg.dpOffBoardKill);
    put(s, "dpmaxiters", g_cfg.dpMaxIters);
    put(s, "dptopstop", g_cfg.dpTopStop);
    put(s, "dpwalkgates", g_cfg.dpWalkGates);
    put(s, "coinmissrev", g_cfg.coinMissRev);
    put(s, "coinmisspost", g_cfg.coinMissPost);
    put(s, "coinoverdepth", g_cfg.coinOverDepth);
    put(s, "coinapproachoff", g_cfg.coinApproachOff);
    put(s, "routeprereq", g_cfg.routePrereq);
    put(s, "routeprereqafter", g_cfg.routePrereqAfter);
    put(s, "coinmissmove", g_cfg.coinMissMove);
    put(s, "groupsretime", g_cfg.groupsRetime);
    put(s, "dpsecauto", g_cfg.dpSecAuto);
    put(s, "dpsecstall", g_cfg.dpSecStall);
    put(s, "dpsecnorec", g_cfg.dpSecNoRec);
    put(s, "dpsecmargin", g_cfg.dpSecMargin);
    put(s, "dpsecchain", g_cfg.dpSecChain);
    put(s, "dpsecchainspan", g_cfg.dpSecChainSpan);
    put(s, "dpsecpinback", g_cfg.dpSecPinBack);
    put(s, "dpsecstateprice", g_cfg.dpSecStatePrice);
    put(s, "dpseccallprice", g_cfg.dpSecCallPrice);
    put(s, "dpseccap", g_cfg.dpSecCap);
    put(s, "dpsecsolved", g_cfg.dpSecSolved);
    put(s, "dpsecreuse", g_cfg.dpSecReuse);
    put(s, "dpsecrent", g_cfg.dpSecRent);
    put(s, "dpsecrungprior", g_cfg.dpSecRungPrior);
    put(s, "dpseccoinrung", g_cfg.dpSecCoinRung);
    put(s, "dpendtrigclear", g_cfg.dpEndTrigClear);
    put(s, "slice", g_cfg.slice);
    put(s, "slicemin", g_cfg.sliceMin);
    put(s, "sliceaddbacks", g_cfg.sliceAddBacks);
    put(s, "slicecount", g_cfg.sliceCount);
    put(s, "slicenoposition", g_cfg.sliceNoPosition);
    put(s, "dpseedplan", g_cfg.dpSeedPlan);
    put(s, "dpshow", g_cfg.dpShow);
    put(s, "dpfixups", g_cfg.dpFixups);
    put(s, "dpworld", g_cfg.dpWorld);
    put(s, "dpgroups", g_cfg.dpGroups);
    put(s, "dpbandtrack", g_cfg.dpBandTrack);
    put(s, "dprotseed", g_cfg.dpRotSeed);
    put(s, "dprotseedanchor", g_cfg.dpRotSeedAnchor);
    put(s, "dpsnapshot", g_cfg.dpSnapshot);
    put(s, "dpcheck", g_cfg.dpCheck);
    put(s, "dpcheckobs", g_cfg.dpCheckObs);
    put(s, "dpcheckfirst", g_cfg.dpCheckFirst);
    put(s, "dpcontenthorizon", g_cfg.dpContentHorizon);
    put(s, "dpcapladder", g_cfg.dpCapLadder);
    put(s, "dpinputgrid", g_cfg.dpInputGrid);
    put(s, "dpphaseprof", g_cfg.dpPhaseProf);
    put(s, "dprotqtoggle", g_cfg.dpRotQToggle);
    put(s, "dpspentpad", g_cfg.dpSpentPad);
    put(s, "dpwatchfired", g_cfg.dpWatchFired);
    put(s, "dpfingerprint", g_cfg.dpFingerprint);
    put(s, "dptouchseednow", g_cfg.dpTouchSeedNow);
    put(s, "dparg", g_cfg.dpArgs);
    put(s, "presstrace", g_pressT0, g_pressT1);
    put(s, "rngfresh", g_rngFresh);
    put(s, "rngseed", g_rngSeedEE0, g_rngSeedEF8);
    put(s, "areatrace", g_areaUids);
    put(s, "sticktrace", g_stickT0, g_stickT1);
    put(s, "slopetrace", g_slopeT0, g_slopeT1);
    return s;
}

}  // namespace effcfg
}  // namespace p1
